name: mopidy_client
description: Mopidy client
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0
homepage: https://github.com/nerk/mopidy_dart_client

environment:
  sdk: '>=3.0.0'

dependencies:
  eventify: ^1.0.0
  recase: ^4.0.0
  format: ^1.4.0
  console: ^4.1.0
  meta: ^1.7.0
  logger: ^2.0.2
  rxdart: ^0.27.7
  web_socket_channel: ^2.4.5
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
  
